apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-docker-deployment
  labels:
    app: flask-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-docker
  template:
    metadata:
      labels:
        app: flask-docker
    spec:
      containers:
      - name: flask-docker
        image: trongnghiattr/flask-docker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3200