apiVersion: v1
kind: Service
metadata:
  name: flask-docker-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: flask-docker-service
spec:
  type: LoadBalancer
  ports:
  - name: flask-docker
    port: 3200
    targetPort: 5000
  selector:
    app: flask-docker
  sessionAffinity: None